project_name: kubeds

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  ignore:
    - goos: darwin
      goarch: 386
  targets:
  - linux_amd64
  - linux_386
  - darwin_amd64
  - darwin_386
  main: ./kubeds
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: kubeds
  lang: go

archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE*
  - README*
  - CHANGELOG*

snapshot:
  name_template: SNAPSHOT-{{ .Timestamp }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none