project_name: leizu
#git:
#  short_hash: true

release:
  github:
    owner: git@git.17bdc.com:earlzo
    name: leizu
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  targets:
  - linux_amd64
  - linux_386
  - darwin_amd64
  - darwin_386
  main: ./leizu
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: leizu
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Timestamp }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
dockers:
  - image: user/repo