# .travis.yml
language: go
go_import_path: github.com/shanbay/kubeds
cache:
  directories:
    - $GOPATH/github.com/shanbay/kubeds/vendor

install:
  - go get -u golang.org/x/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -update -v

services:
  - docker

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      script: golint -set_exit_status
    - stage: test
      script: go test
    - stage: deploy
      skip_cleanup: true
      script: curl -sL http://git.io/goreleaser | bash
      on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux