# .travis.yml
language: go
go_import_path: github.com/shanbay/kubeds
cache:
  directories:
    - $GOPATH/github.com/shanbay/kubeds/vendor

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - go get -u golang.org/x/lint/golint
        - golint -set_exit_status
    - stage: test
      script:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure -update -v
        - go test
    - stage: deploy
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL http://git.io/goreleaser | bash
        on:
          tags: true
          branch: master
          condition: $TRAVIS_OS_NAME = linux