# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]

[[constraint]]
    name = "github.com/spf13/cobra"
    branch = "master"

[[constraint]]
    name = "github.com/spf13/viper"
    branch = "master"

[[constraint]]
    name = "github.com/sirupsen/logrus"
    version = "^1.0.5"

[[constraint]]
    name = "google.golang.org/grpc"
    version = "^1.10.0"

[[constraint]]
    name = "github.com/envoyproxy/go-control-plane"
    branch="master"

# https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet
[[constraint]]
    name = "k8s.io/client-go"
    branch = "release-5.0"

[[constraint]]
    name = "k8s.io/api"
    branch = "release-1.8"

[[constraint]]
    name = "k8s.io/apimachinery"
    branch = "release-1.8"

[prune]
   non-go = true
   go-tests = true
   # unused-packages = true
